# Generated by Django 4.1.1 on 2022-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_watchlist', '0003_streamplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
