# Generated by Django 4.1.1 on 2022-09-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_watchlist', '0004_streamplatform_active_streamplatform_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='apps_watchlist.streamplatform'),
            preserve_default=False,
        ),
    ]
