# Generated by Django 4.1.1 on 2022-09-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_watchlist', '0006_alter_watchlist_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
    ]
